function main() {
    startApplication("umbrello");
    clickButton(waitForObject(":Untitled – Umbrello UML Modeller.Class_QToolButton"));
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView"), QEvent.MouseButtonPress, 95, 76, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView"), QEvent.MouseButtonRelease, 95, 76, Qt.LeftButton, 1);
    type(waitForObject(":Enter name:_KLineEdit"), "Q#Canvas");
    mouseClick(waitForObject(":Enter name:_KLineEdit"), 18, 10, 0, Qt.LeftButton);
    type(waitForObject(":Enter name:_KLineEdit"), "<Del>");
    type(waitForObject(":Enter name:_KLineEdit"), "3");
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonPress, 35, 23, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonRelease, 35, 23, Qt.LeftButton, 1);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView"), 130, 195, 0, Qt.LeftButton);
    type(waitForObject(":Enter name:_KLineEdit"), "Q3CanvasView");
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonPress, 19, 12, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonRelease, 19, 12, Qt.LeftButton, 1);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView"), 264, 152, 0, Qt.LeftButton);
    type(waitForObject(":Enter name:_KLineEdit"), "UMLView");
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonPress, 15, 9, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonRelease, 15, 9, Qt.LeftButton, 1);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView"), 396, 253, 0, Qt.LeftButton);
    type(waitForObject(":Enter name:_KLineEdit"), "UMLViewCanvas");
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonPress, 35, 12, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonRelease, 35, 12, Qt.LeftButton, 1);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView"), 450, 151, 0, Qt.LeftButton);
    type(waitForObject(":Enter name:_KLineEdit"), "UMLView");
    type(waitForObject(":Enter name:_KLineEdit"), "<Return>");
    sendEvent("QMouseEvent", waitForObject(":Not a Unique Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonPress, 29, 2, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":Not a Unique Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonRelease, 29, 2, Qt.LeftButton, 1);
    type(waitForObject(":Enter name:_KLineEdit"), "Q3CanvasLine");
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonPress, 25, 14, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonRelease, 25, 14, Qt.LeftButton, 1);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView"), 199, 66, 0, Qt.LeftButton);
    type(waitForObject(":Enter name:_KLineEdit"), "Q3Canvasll");
    type(waitForObject(":Enter name:_KLineEdit"), "<Backspace>");
    type(waitForObject(":Enter name:_KLineEdit"), "<Backspace>");
    type(waitForObject(":Enter name:_KLineEdit"), "Ellipse");
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonPress, 14, 8, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonRelease, 14, 8, Qt.LeftButton, 1);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView"), 294, 265, 0, Qt.LeftButton);
    type(waitForObject(":Enter name:_KLineEdit"), "SubsetSymbol");
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonPress, 39, 13, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonRelease, 38, 13, Qt.LeftButton, 1);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView"), 423, 93, 0, Qt.LeftButton);
    type(waitForObject(":Enter name:_KLineEdit"), "Circle");
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonPress, 12, 3, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonRelease, 12, 3, Qt.LeftButton, 1);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView"), 406, 193, 0, Qt.LeftButton);
    type(waitForObject(":Enter name:_KLineEdit"), "LinePath");
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonPress, 9, 10, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonRelease, 9, 10, Qt.LeftButton, 1);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView"), 338, 100, 0, Qt.LeftButton);
    clickButton(waitForObject(":Name – Umbrello UML Modeller.Cancel_KPushButton"));
    clickButton(waitForObject(":Untitled – Umbrello UML Modeller.Select_QToolButton"));
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView"), 113, 93, -65, -50, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 59, 54, 127, 3, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 222, 81, 45, -40, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 270, 55, 122, 5, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 325, 46, 258, 4, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 436, 109, -17, 28, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 148, 209, -82, 29, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 73, 253, 117, 14, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 142, 250, 184, -204, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 380, 64, 29, -4, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 360, 41, 5, 5, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 564, 48, -465, 192, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 288, 162, -29, 58, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 313, 286, 197, 28, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 263, 239, 78, 12, 1, Qt.LeftButton);
    sendEvent("QMouseEvent", waitForObject(":Untitled [modified] – Umbrello UML Modeller_QToolButton"), QEvent.MouseButtonPress, 19, 7, Qt.LeftButton, 0);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 418, 202, -309, 97, 1, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 305, 215, 0, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 338, 250, 27, -9, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 320, 226, -10, 8, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 356, 250, 10, 7, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 324, 240, 31, -79, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 399, 177, 15, 3, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 352, 160, -14, -14, 1, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 413, 139, 0, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 406, 264, 0, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 423, 277, 110, -6, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 469, 261, -365, -131, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 172, 144, 39, 8, 1, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 313, 156, 0, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 329, 154, 2, -11, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 405, 157, 12, -6, 1, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 429, 145, 0, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 425, 137, 148, 2, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 582, 151, 90, -2, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 621, 139, -380, 206, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 116, 237, 165, 36, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 211, 338, 63, 20, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 122, 314, -40, 39, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 158, 358, -7, -8, 1, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 134, 316, 0, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 150, 358, 54, -39, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 170, 303, -51, 43, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 155, 360, 29, 6, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 129, 343, 2, 11, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 181, 379, 10, -2, 1, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 509, 314, 0, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 501, 303, -66, 7, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 454, 327, 99, 5, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 503, 319, -26, 40, 1, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 471, 163, 0, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 479, 176, 93, 8, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 490, 172, 85, -79, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 657, 110, 14, -2, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 601, 84, -30, 89, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 258, 273, -33, -29, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 111, 368, -16, -15, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 261, 373, -9, -19, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 439, 364, 2, -15, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 572, 179, 61, -107, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 703, 89, 25, 1, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 663, 63, -23, -12, 1, Qt.LeftButton);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Implements_QToolButton"));
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 92, 125, 8, -70, 1, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 100, 49, 0, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 298, 137, 7, -81, 1, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 304, 52, 0, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 119, 340, 97, -92, 1, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 214, 250, 0, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 263, 340, -15, -86, 1, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 248, 256, 0, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 448, 344, -151, -89, 1, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 295, 256, 0, Qt.LeftButton);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Select_QToolButton"));
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 202, 235, 31, -13, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 98, 350, -5, -8, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 235, 236, -35, -2, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 164, 339, 25, 3, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 264, 351, -10, -6, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 178, 349, -13, -5, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 435, 345, -47, -2, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 305, 226, 27, -2, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 313, 353, -10, -7, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 326, 342, 5, 7, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 425, 349, -4, -7, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 320, 229, 14, 3, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 357, 250, 27, 6, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 345, 242, -23, -1, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 410, 324, -7, 1, 1, Qt.LeftButton);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonPress, 284, 328, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonRelease, 283, 327, Qt.LeftButton, 1);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Directional Association_QToolButton"));
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 209, 147, 77, -5, 1, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 262, 133, 0, Qt.LeftButton);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Select_QToolButton"));
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 147, 143, -6, -16, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 321, 141, -7, -6, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 112, 64, -45, -5, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 93, 55, 7, -2, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 347, 65, 2, -2, 1, Qt.LeftButton);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Implements_QToolButton"));
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 244, 48, -61, -4, 1, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 183, 44, 0, Qt.LeftButton);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Select_QToolButton"));
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 99, 44, 2, 3, 1, Qt.LeftButton);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonPress, 308, 36, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonRelease, 310, 35, Qt.LeftButton, 1);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Class_QToolButton"));
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonPress, 545, 157, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonRelease, 545, 157, Qt.LeftButton, 1);
    type(waitForObject(":Enter name:_KLineEdit"), "SeqLineWidget");
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonPress, 38, 12, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonRelease, 38, 12, Qt.LeftButton, 1);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonPress, 611, 292, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonRelease, 611, 292, Qt.LeftButton, 1);
    type(waitForObject(":Enter name:_KLineEdit"), "ObjectWidget");
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonPress, 40, 14, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonRelease, 40, 14, Qt.LeftButton, 1);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Select_QToolButton"));
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonPress, 634, 312, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonRelease, 562, 266, Qt.LeftButton, 1);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 591, 70, -49, -10, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 562, 52, 38, 24, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 560, 178, -46, -7, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 572, 184, 121, 6, 1, Qt.LeftButton);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonPress, 630, 307, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonRelease, 630, 307, Qt.LeftButton, 1);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonPress, 624, 309, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonRelease, 537, 257, Qt.LeftButton, 1);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 642, 321, 96, -14, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 681, 309, -103, -49, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 683, 304, -50, -17, 67108865, Qt.LeftButton);
    type(waitForObject(":Untitled [modified] – Umbrello UML Modeller_KTabBar"), "<Shift>");
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 660, 305, -43, -32, 33554433, Qt.LeftButton);
    type(waitForObject(":Untitled [modified] – Umbrello UML Modeller_KTabBar"), "<Shift>");
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonPress, 633, 311, Qt.LeftButton, 100663296);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonRelease, 631, 307, Qt.LeftButton, 100663297);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonDblClick, 631, 307, Qt.LeftButton, 100663296);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 633, 311, -11, -51, 100663297, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 619, 300, -33, -22, 100663297, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 688, 289, 26, 10, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 647, 287, -21, -11, 67108865, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 611, 75, 9, 7, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 632, 174, 2, 8, 1, Qt.LeftButton);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Implements_QToolButton"));
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 602, 178, -9, -86, 1, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 600, 89, 0, Qt.LeftButton);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Directional Association_QToolButton"));
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 591, 195, 26, 84, 1, Qt.LeftButton);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonPress, 615, 274, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonRelease, 615, 274, Qt.LeftButton, 1);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Select_QToolButton"));
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 649, 289, 2, -4, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 597, 173, -3, 7, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 603, 80, -1, 7, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 314, 237, -7, -4, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 143, 336, -1, -11, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 302, 322, -30, 43, 1, Qt.LeftButton);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonPress, 297, 355, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonRelease, 298, 353, Qt.LeftButton, 1);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 261, 374, 26, -36, 1, Qt.LeftButton);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonPress, 289, 340, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonRelease, 289, 340, Qt.LeftButton, 1);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 282, 339, 1, -12, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 379, 337, 3, -5, 1, Qt.LeftButton);
    openContextMenu(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 176, 298, 0);
    openContextMenu(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 176, 274, 0);
    openContextMenu(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 178, 263, 0);
    activateItem(waitForObjectItem(":Untitled [modified] – Umbrello UML Modeller_ListPopupMenu", "Properties"));
    waitForObjectItem(":_KDEPrivate::KPageListView", "Roles");
    clickItem(":_KDEPrivate::KPageListView", "Roles", 48, 22, 0, Qt.LeftButton);
    mouseClick(waitForObject(":Multiplicity:_KLineEdit"), 83, 9, 0, Qt.LeftButton);
    waitForObjectItem(":_KDEPrivate::KPageListView", "General");
    clickItem(":_KDEPrivate::KPageListView", "General", 48, 33, 0, Qt.LeftButton);
    mouseClick(waitForObject(":Type:_KComboBox"), 258, 15, 0, Qt.LeftButton);
    mouseClick(waitForObject(":Type:_KComboBox"), 303, 14, 0, Qt.LeftButton);
    sendEvent("QMouseEvent", waitForObject(":Type:_KComboBox"), QEvent.MouseButtonPress, 302, -8, Qt.LeftButton, 0);
    waitForObjectItem(":_KDEPrivate::KPageListView", "Roles");
    clickItem(":_KDEPrivate::KPageListView", "Roles", 40, 28, 0, Qt.LeftButton);
    clickButton(waitForObject(":Cancel_KPushButton"));
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Save_QToolButton"));
    clickButton(waitForObject(":Save As – Umbrello UML Modeller.Parent Folder_QToolButton"));
    clickButton(waitForObject(":Save As – Umbrello UML Modeller.Parent Folder_QToolButton"));
    clickButton(waitForObject(":Save As – Umbrello UML Modeller.Parent Folder_QToolButton"));
    waitForObjectItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "test");
    clickItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "test", 133, 5, 0, Qt.LeftButton);
    waitForObjectItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "kdesdk");
    clickItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "kdesdk", 94, 6, 0, Qt.LeftButton);
    waitForObjectItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "krazy-krazy");
    clickItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "krazy-krazy", 88, 6, 0, Qt.LeftButton);
    waitForObjectItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "test");
    clickItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "test", 78, 8, 0, Qt.LeftButton);
    scrollTo(waitForObject(":Save As – Umbrello UML Modeller_QScrollBar"), 186);
    waitForObjectItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "qt-snake");
    clickItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "qt-snake", 85, 9, 0, Qt.LeftButton);
    sendEvent("QWheelEvent", waitForObject(":Save As – Umbrello UML Modeller_KDirOperatorDetailView"), 97, 128, 120, 0, 2);
    sendEvent("QWheelEvent", waitForObject(":Save As – Umbrello UML Modeller_KDirOperatorDetailView"), 98, 128, 360, 0, 2);
    waitForObjectItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "test");
    clickItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "test", 49, 11, 0, Qt.LeftButton);
    waitForObjectItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "squish-4\\.1-20110401-1553-kde4-linux32");
    clickItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "squish-4\\.1-20110401-1553-kde4-linux32", 82, 6, 0, Qt.LeftButton);
    waitForObjectItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "tcc-senacrs-camila-ayres");
    doubleClickItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "tcc-senacrs-camila-ayres", 79, 14, 0, Qt.LeftButton);
    waitForObjectItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "testes");
    doubleClickItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "testes", 51, 7, 0, Qt.LeftButton);
    mouseClick(waitForObject(":Name:_KLineEdit"), 64, 7, 0, Qt.LeftButton);
    type(waitForObject(":Name:_KUrlComboBox"), "T");
    type(waitForObject(":Name:_KUrlComboBox"), "E");
    type(waitForObject(":Name:_KUrlComboBox"), "S");
    type(waitForObject(":Name:_KUrlComboBox"), "T");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "t");
    type(waitForObject(":Name:_KUrlComboBox"), "e");
    type(waitForObject(":Name:_KUrlComboBox"), "s");
    type(waitForObject(":Name:_KUrlComboBox"), "t");
    type(waitForObject(":Name:_KUrlComboBox"), "_");
    type(waitForObject(":Name:_KUrlComboBox"), "c");
    type(waitForObject(":Name:_KUrlComboBox"), "a");
    type(waitForObject(":Name:_KUrlComboBox"), "n");
    type(waitForObject(":Name:_KUrlComboBox"), "v");
    type(waitForObject(":Name:_KUrlComboBox"), "a");
    type(waitForObject(":Name:_KUrlComboBox"), "s");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Name:_KUrlComboBox"), "c");
    type(waitForObject(":Name:_KUrlComboBox"), "l");
    type(waitForObject(":Name:_KUrlComboBox"), "a");
    type(waitForObject(":Name:_KUrlComboBox"), "s");
    type(waitForObject(":Name:_KUrlComboBox"), "s");
    type(waitForObject(":Name:_KUrlComboBox"), "_");
    type(waitForObject(":Name:_KUrlComboBox"), "d");
    type(waitForObject(":Name:_KUrlComboBox"), "i");
    type(waitForObject(":Name:_KUrlComboBox"), "a");
    type(waitForObject(":Name:_KUrlComboBox"), "g");
    type(waitForObject(":Name:_KUrlComboBox"), "r");
    type(waitForObject(":Name:_KUrlComboBox"), "a");
    type(waitForObject(":Name:_KUrlComboBox"), "m");
    type(waitForObject(":Name:_KUrlComboBox"), "_");
    type(waitForObject(":Name:_KUrlComboBox"), "c");
    type(waitForObject(":Name:_KUrlComboBox"), "a");
    type(waitForObject(":Name:_KUrlComboBox"), "n");
    type(waitForObject(":Name:_KUrlComboBox"), "v");
    type(waitForObject(":Name:_KUrlComboBox"), "a");
    type(waitForObject(":Name:_KUrlComboBox"), "s");
    type(waitForObject(":Name:_KUrlComboBox"), ".");
    type(waitForObject(":Name:_KUrlComboBox"), "x");
    type(waitForObject(":Name:_KUrlComboBox"), "m");
    type(waitForObject(":Name:_KUrlComboBox"), "i");
    clickButton(waitForObject(":Save As – Umbrello UML Modeller.Save_KPushButton"));
    sendEvent("QCloseEvent", waitForObject(":class_diagram_canvas.xmi – Umbrello UML Modeller_UMLApp"));
}

