function main() {
    startApplication("umbrello");
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Class_QToolButton"));
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView"), QEvent.MouseButtonPress, 232, 99, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView"), QEvent.MouseButtonRelease, 232, 99, Qt.LeftButton, 1);
    type(waitForObject(":Enter name:_KLineEdit"), "QE");
    type(waitForObject(":Enter name:_KLineEdit"), "<Backspace>");
    type(waitForObject(":Enter name:_KLineEdit"), "3Canvas");
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonPress, 31, 9, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonRelease, 31, 9, Qt.LeftButton, 1);
    clickButton(waitForObject(":Untitled – Umbrello UML Modeller.Select_QToolButton"));
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView"), 247, 103, -85, -30, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 176, 97, 208, 8, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 303, 87, 33, -24, 1, Qt.LeftButton);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Class_QToolButton"));
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 190, 181, 0, Qt.LeftButton);
    type(waitForObject(":Enter name:_KLineEdit"), "Q3CanvasView");
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonPress, 41, 19, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonRelease, 41, 19, Qt.LeftButton, 1);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Select_QToolButton"));
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 200, 194, -16, -49, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 202, 162, 213, 18, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 282, 133, 0, -5, 1, Qt.LeftButton);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Class_QToolButton"));
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 208, 224, 0, Qt.LeftButton);
    type(waitForObject(":Enter name:_KLineEdit"), "Q3CanvasItem");
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonPress, 16, 9, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":Name – Umbrello UML Modeller.OK_KPushButton"), QEvent.MouseButtonRelease, 16, 9, Qt.LeftButton, 1);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Select_QToolButton"));
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 225, 241, -42, -3, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 196, 249, 219, 19, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 280, 234, 5, 31, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 249, 133, -1, 36, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 256, 73, -10, 21, 1, Qt.LeftButton);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Directional Association_QToolButton"));
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 283, 180, -1, -77, 1, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 280, 88, 0, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 256, 272, 0, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 261, 196, 0, Qt.LeftButton);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Select_QToolButton"));
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 264, 269, 17, 27, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 283, 176, -17, 10, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 272, 88, -14, 6, 1, Qt.LeftButton);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonPress, 259, 232, Qt.LeftButton, 0);
    sendEvent("QMouseEvent", waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), QEvent.MouseButtonRelease, 259, 232, Qt.LeftButton, 1);
    type(waitForObject(":Untitled [modified] – Umbrello UML Modeller_KTabBar"), "<Del>");
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Implements_QToolButton"));
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 281, 300, 0, Qt.LeftButton);
    mouseClick(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 289, 208, 0, Qt.LeftButton);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Select_QToolButton"));
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 237, 295, -45, 16, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 253, 178, -24, 5, 1, Qt.LeftButton);
    mouseDrag(waitForObject(":qt_tabwidget_stackedwidget_UMLView_2"), 249, 96, -25, 7, 1, Qt.LeftButton);
    clickButton(waitForObject(":Untitled [modified] – Umbrello UML Modeller.Save_QToolButton"));
    mouseClick(waitForObject(":_KLineEdit"), 219, 7, 0, Qt.LeftButton);
    mouseDrag(waitForObject(":_KLineEdit"), 196, 8, 168, 2, 1, Qt.LeftButton);
    type(waitForObject(":Save As – Umbrello UML Modeller_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Save As – Umbrello UML Modeller_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Save As – Umbrello UML Modeller_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Save As – Umbrello UML Modeller_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Save As – Umbrello UML Modeller_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Save As – Umbrello UML Modeller_KUrlComboBox"), "<Backspace>");
    type(waitForObject(":Save As – Umbrello UML Modeller_KUrlComboBox"), "t");
    type(waitForObject(":Save As – Umbrello UML Modeller_KUrlComboBox"), "c");
    type(waitForObject(":Save As – Umbrello UML Modeller_KUrlComboBox"), "c");
    type(waitForObject(":Save As – Umbrello UML Modeller_KUrlComboBox"), "<Down>");
    type(waitForObject(":Save As – Umbrello UML Modeller_KUrlComboBox"), "<Return>");
    waitForObjectItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "testes");
    doubleClickItem(":Save As – Umbrello UML Modeller_KDirOperatorDetailView", "testes", 44, 8, 0, Qt.LeftButton);
    mouseClick(waitForObject(":Name:_KLineEdit"), 97, 5, 0, Qt.LeftButton);
    type(waitForObject(":Name:_KUrlComboBox"), "t");
    type(waitForObject(":Name:_KUrlComboBox"), "e");
    type(waitForObject(":Name:_KUrlComboBox"), "s");
    type(waitForObject(":Name:_KUrlComboBox"), "t");
    type(waitForObject(":Name:_KUrlComboBox"), "e");
    type(waitForObject(":Name:_KUrlComboBox"), "2");
    type(waitForObject(":Name:_KUrlComboBox"), ".");
    type(waitForObject(":Name:_KUrlComboBox"), "x");
    type(waitForObject(":Name:_KUrlComboBox"), "m");
    type(waitForObject(":Name:_KUrlComboBox"), "i");
    clickButton(waitForObject(":Save As – Umbrello UML Modeller.Save_KPushButton"));
    sendEvent("QCloseEvent", waitForObject(":teste2.xmi – Umbrello UML Modeller_UMLApp"));
}

